# Krypton Configuration
# Plugin by Archyx

captcha:
  mode: MAP
  every_join: false
  enable_fail_kick: true
  fail_kick_max_attempts: 5
  enable_on_startup: true
  map:
    code_length: 5
    use_numbers: true
    use_capital_letters: true
    block_look: false
    use_protocol_lib: true
    allow_move:
      enabled: false
      duration_ticks: 5
    force_pitch:
      enabled: false
      pitch: 80.0
  menu:
    reopen_delay: 40

api_mode: false