name: Krypton
version: ${project.version}
main: com.archyx.krypton.Krypton
api-version: 1.15
authors: [ Archyx ]
softdepend: [ ProtocolLib ]
description: An advanced captcha plugin to stop bots on your server

permissions:
  krypton.reload:
    default: op
  krypton.unlock:
    default: op
